#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/Simon/neuron/nrn"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/Simon/neuron/nrn/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/Simon/NML2_Test/AOB_mitral_cell/x86_64/.libs/libnrnmech.so" "$@"
